# Specify a directory to install
cask_args appdir: '/Applications'
# Install Packages
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "apr-util"
brew "cmake"
brew "cowsay"
brew "curl"
brew "wget"
brew "fortune"
brew "freetds"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "git-secret"
brew "httpd"
brew "krb5"
brew "libfido2"
brew "libpq"
brew "python@3.10"
brew "llvm"
brew "mysql"
brew "nvm"
brew "openvpn"
brew "php"
brew "python@3.9"
brew "ragel"
brew "sassc"
brew "yarn"
